### ISSUE TITLE
error

### ISSUE THREAD

**Issue by HanifWadowsky** [soradore/GoCart#2]
Server thread/CRITICAL]: ArgumentCountError: "Too few arguments to function pocketmine\network\mcpe\protocol\types\EntityLink::__construct(), 3 passed in /storage/emulated/0/Android/data/io.scer.pocketmine/files/PocketMine-MP/plugins/GoCart-master/src/soradore/gocart/entity/Minecart.php on line 58 and exactly 5 expected" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/types/EntityLink" at line 43

**Comment by soradore** [comment]
Maybe it's fixed.
